general.live_config_reload = true

[window]
decorations = "none"
opacity = 0.6

[font]
normal = { family = "Inconsolata", style = "Regular" }
bold = { family = "Inconsolata", style = "Bold" }
italic = { family = "Inconsolata", style = "Italic" }
bold_italic = { family = "Inconsolata", style = "Bold Italic" }
size = 10.0

[colors.primary]
foreground = "#b0b0b0"
background = "#252528"

[colors.cursor]
text = "#252528"
cursor = "#7a9099"

[colors.selection]
text = "#c8c8c0"
background = "#333333"

[colors.normal]
black = "#26252c"
red = "#8a5555"
green = "#656555"
yellow = "#8a7548"
blue = "#6b8ba3"
magenta = "#7d6f8a"
cyan = "#5f8a8a"
white = "#a8a8a0"

[colors.bright]
black = "#555555"
red = "#a56b6b"
green = "#858575"
yellow = "#a8916a"
blue = "#89a8bd"
magenta = "#948aa0"
cyan = "#7aa5a5"
white = "#c0c0b8"